version: '3.8'

services:
  db:
    image: postgres:15
    container_name: motorcycle_rentail_postgres
    restart: always
    environment:
      POSTGRES_USER: motorcycle_rentail
      POSTGRES_PASSWORD: rentail123
      POSTGRES_DB: motorcycle_rentail_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: motorcycle_rentail_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
